#!/bin/bash

function listkernel()
{
    find arch/x86 block Documentation drivers fs include init ipc kernel lib mm net tools usr virt \
    \( -path "*crypto" -o -path "*git*" -o -path "*gpu*" -o -path "*firmware*" -o -path "*macintosh*" \
	-o -path "*s390*" -o -path "*video*" -o -path "*media*" -o -path "*infiniband*" -o -path "*usb*" \
	-o -path "*staging*" -o -path "*sound*" -o -path "*soc*" -o -path "*powerpc*" -o -path "*mips*" \
	-o -path "*arm*" -o -path "*alpha*" -o -path "*sparc*" -o -path "*xen*" -o -path "*bluetooth*" \
	-o -path "*input*" -o -path "*generated*" -o -path "*testing*"  -o -path "*include\/config*" \
	-o -path "*android*" -o -path "*display*" -o -path "*wireless*" -o -path "*nfc*" -o -path "ocfs2" \
    -o -path "*reiserfs*" -o -path "*cachefiles*" -o -path "*adfs*" -o -path "*ecryptfs*" -o -path "*befs*"  \
    -o -path "*orangefs*" -o -path "*ufs*" -o -path "*jffs2*" -o -path "*isofs*" -o -path "*affs*"  \
    -o -path "*cramfs*" -o -path "*dlm*" -o -path "*qnx6*" -o -path "*crypto*" -o -path "*afs*"  \
    -o -path "*freevxfs*" -o -path "*qnx4*" -o -path "*efs*" -o -path "*nls*" -o -path "*jfs*"  \
    -o -path "*hfsplus*" -o -path "*romfs*" -o -path "*9p*" -o -path "*hfs*" -o -path "*gfs2*" -o -path "*omfs*" \
    -o -path "*nfsd*" -o -path "*nilfs2*" -o -path "*coda*" -o -path "*devpts*" -o -path "*configfs*"  \
    -o -path "*fat*" -o -path "*exofs*" -o -path "*sysv*" -o -path "*efivarfs*" -o -path "*exportfs*"  \
    -o -path "*ubifs*" -o -path "*f2fs*" -o -path "*pstore*" -o -path "*cifs*" -o -path "fs\/bfs*"  \
    -o -path "*hpfs*" -o -path "*openpromfs*" -o -path "*minix*" -o -path "*btrfs*" -o -path "*udf*" \
    -o -path "drivers\/accessibility*" -o -path "drivers\/amba*" -o -path "drivers\/android*" -o -path "drivers\/atm*"  \
    -o -path "drivers\/auxdisplay*" -o -path "drivers\/bcma*" -o -path "drivers\/bluetooth*" -o -path "drivers\/cdrom*"  \
    -o -path "drivers\/connector*" -o -path "drivers\/crypto*" -o -path "drivers\/dca*" -o -path "drivers\/edac*"  \
    -o -path "drivers\/eisa*" -o -path "drivers\/extcon*" -o -path "drivers\/firewire*" -o -path "drivers\/firmware*"  \
    -o -path "drivers\/fmc*" -o -path "drivers\/fpga*" -o -path "drivers\/fsi*" -o -path "drivers\/gnss*"  \
    -o -path "drivers\/gpu*" -o -path "drivers\/hid*" -o -path "drivers\/hsi*" -o -path "drivers\/i2c*"  \
    -o -path "drivers\/i3c*" -o -path "drivers\/iio*" -o -path "drivers\/infiniband*" -o -path "drivers\/input*"  \
    -o -path "drivers\/ipack*" -o -path "drivers\/isdn*" -o -path "drivers\/leds*" -o -path "drivers\/macintosh*"  \
    -o -path "drivers\/mailbox*" -o -path "drivers\/mcb*" -o -path "drivers\/md*" -o -path "drivers\/media*"  \
    -o -path "drivers\/memstick*" -o -path "drivers\/message*" -o -path "drivers\/mfd*" -o -path "drivers\/mmc*"  \
    -o -path "drivers\/mtd*" -o -path "drivers\/mux*" -o -path "drivers\/nfc*" -o -path "drivers\/ntb*"  \
    -o -path "drivers\/nubus*" -o -path "drivers\/of*" -o -path "drivers\/opp*" -o -path "drivers\/parisc*"  \
    -o -path "drivers\/parport*" -o -path "drivers\/pcmcia*" -o -path "drivers\/phy*" -o -path "drivers\/pinctrl*"  \
    -o -path "drivers\/pnp*" -o -path "drivers\/power*" -o -path "drivers\/powercap*" -o -path "drivers\/pps*"  \
    -o -path "drivers\/ps3*" -o -path "drivers\/ptp*" -o -path "drivers\/pwm*" -o -path "drivers\/rapidio*"  \
    -o -path "drivers\/regulator*" -o -path "drivers\/remoteproc*" -o -path "drivers\/rpmsg*" -o -path "drivers\/s390*"  \
    -o -path "drivers\/sbus*" -o -path "drivers\/sfi*" -o -path "drivers\/sh*" -o -path "drivers\/siox*"  \
    -o -path "drivers\/slimbus*" -o -path "drivers\/sn*" -o -path "drivers\/soc*" -o -path "drivers\/soundwire*"  \
    -o -path "drivers\/spi*" -o -path "drivers\/spmi*" -o -path "drivers\/ssb*" -o -path "drivers\/staging*"  \
    -o -path "drivers\/tc*" -o -path "drivers\/tee*" -o -path "drivers\/thermal*" -o -path "drivers\/usb*"  \
    -o -path "drivers\/uwb*" -o -path "drivers\/video*" -o -path "drivers\/visorbus*" -o -path "drivers\/vlynq*"  \
    -o -path "drivers\/vme*" -o -path "drivers\/w1*" -o -path "drivers\/xen*" -o -path "drivers\/zorro*" \
    \) -prune -o -type f -name "*.[c,h,txt,S]" -print | sort | uniq -i
}

function listqemu()
{
    find . \
    \( -path "*test*" -o -path "*stub*" -o -path "*git*" -o -path "*tcg*" -o -path "*audio*" \
	-o -path "*bsd*" -o -path "*contrib*" -o -path "*crypto*" -o -path "*alpha*" -o -path "*arm*" \
	-o -path "*hppa*" -o -path "*cris*" -o -path "*i2c*" -o -path "*ipack*" -o -path "*lm32*" \
	-o -path "*m68k*" -o -path "*microblaze*" -o -path "*mips*" -o -path "*moxie*" -o -path "*nios2*" \
	-o -path "*openrisc*" -o -path "*ppc*" -o -path "*pcmcia*" -o -path "*s390x*" -o -path "*sh4*" \
	-o -path "*sparc*" -o -path "*unicore32*" -o -path "*xtensa*" -o -path "*bios*" -o -path "*rom*" \
	-o -path "*pixman*" -o -path "*tricore*" -o -path "*script*" \) -prune \
    -o -type f -name "*.[c,h,txt,S]" -print | sort | uniq -i
}

function listother()
{
    if [ -d ".git" ];then
        git ls-files
    else
        find . -type f -name "*.[c,h,txt,s,S,go,py,sh,vim,cpp,cc]"
    fi
}

function get_project_type()
{
    if [ -d "kernel" -a -d 'arch' -a -d 'virt' -a -d 'net' ];then
        echo kernel
        return
    fi

    if [ -d "accel" -a -d "tcg" -a -d "qapi" ];then
        echo qemu
        return
    fi

    echo other
}

function main()
{
    if [ -z "$1"];then
       root="."
    else
        root="$1"
    fi

    pushd "${root}" > /dev/null
    project_type="$(get_project_type)"
    eval "list${project_type}"
    popd > /dev/null
}

main $@
exit $?
